### PR TITLE
Update organization resource schema

### LINKED ISSUE #65: [Feature Request] Retrieve Snyk Organization slug
### Terraform Version
```shell
terraform -v
Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.44.0
+ provider registry.terraform.io/hashicorp/vault v3.11.0
+ provider registry.terraform.io/lendi-au/snyk v0.2.0
```

### Affected Resource(s)
- `snyk_organization`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "snyk_organization" "snyk_orgs" {
  for_each = local.orgs
  name     = each.value.name
}

output "snyk_orgs" {
  description = "Snyk Organizations"
  value       = snyk_organization.snyk_orgs
}
```

### Expected Behavior
Output should show more than just `name`

### Actual Behavior

Only a list of `name`s were returned. I see in the code, the `Organization` struct fetches the slug from the API:
https://github.com/lendi-au/terraform-provider-snyk/blob/a70b4a8a22f45296ce0cf18c934f21dee4c2dfc3/snyk/api/organization.go#L9-L15

### PR DESCRIPTION
**Pull request by johnjelinek**
Include additional fields from the API: `created`, `slug`, `url`. Fixes #65.

### CODE REVIEW

**Review by paxmarc — APPROVED** [review]

**Comment by paxmarc** [comment]
Thanks @johnjelinek - will push out a release 👍

**Comment by johnjelinek** [comment]
```terraform
      ~ key     = {
          + created      = null
            id           = "d...a"
            name         = "S...g"
          + slug         = "s...8"
          + url          = "https://app.snyk.io/org/s...8"
        }
```
It looks like everything is working, except for `created`. I'm not sure why.

**Comment by johnjelinek** [comment]
@paxmarc: I get this from the API:
```json
{
  "id": "d...a",
  "name": "S...g",
  "slug": "s...8",
  "url": "h...8",
  "created": "2021-08-16T21:32:21.692Z"
}
```

```terraform
      ~ key     = {
          + created      = null
            id           = "d...a"
            name         = "S...g"
          + slug         = "s...8"
          + url          = "https://app.snyk.io/org/s...8"
        }
```
It looks like everything is working, except for `created`. I'm not sure why.

**Comment by johnjelinek** [comment]
[oic](https://github.com/lendi-au/terraform-provider-snyk/actions/runs/4169028366/jobs/7216514426#step:5:41)

**Comment by paxmarc** [comment]
Yeah 😅 could just be a typing issue? I'll have a look. Also haven't updated the repo in a while, so needs some housekeeping on the automation side.

**Comment by johnjelinek** [comment]
@paxmarc: I have fixed this in #67.

**Pull request merged**
